use_frameworks!

platform :ios, '8.0'

target 'TestSDK_Example' do
  pod 'TestSDK', :path => '../'

  target 'TestSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
